In [6]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

## Importing the dataset

In [7]:
patients = pd.read_csv('patients.csv')
treatment = pd.read_csv('treatments.csv')
adversity = pd.read_csv('adverse_reactions.csv')

In [8]:
patients.head(40)

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,male,LiÃªm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1
5,6,male,Rafael,Costa,1140 Willis Avenue,Daytona Beach,Florida,32114.0,United States,386-334-5237RafaelCardosoCosta@gustr.com,8/31/1931,183.9,70,26.4
6,7,female,Mary,Adams,3145 Sheila Lane,Burbank,NV,84728.0,United States,775-533-5933MaryBAdams@einrot.com,11/19/1969,146.3,65,24.3
7,8,female,Xiuxiu,Chang,2687 Black Oak Hollow Road,Morgan Hill,CA,95037.0,United States,XiuxiuChang@einrot.com1 408 778 3236,8/13/1958,158.0,60,30.9
8,9,male,Dsvid,Gustafsson,1790 Nutter Street,Kansas City,MO,64105.0,United States,816-265-9578DavidGustafsson@armyspy.com,3/6/1937,163.9,66,26.5
9,10,female,Sophie,Cabrera,3303 Anmoore Road,New York,New York,10011.0,United States,SophieCabreraIbarra@teleworm.us1 718 795 9124,12/3/1930,194.7,64,33.4
10,11,female,Sandy,Gunnarsson,87 Wood Duck Drive,Rudyard,MI,49780.0,United States,906-478-8949SandyGunnarsson@dayrep.com,7/16/1974,199.3,62,36.4
11,12,male,Abdul-Nur,Isa,1092 Farm Meadow Drive,Brentwood,TN,37027.0,United States,Abdul-NurMummarIsa@rhyta.com1 931 207 0839,2/3/1954,238.7,73,31.5
12,13,male,Omeokachie,Ibeamaka,2544 Worley Avenue,Lynchburg,VA,24504.0,United States,OmeokachieIbeamaka@einrot.com434-509-2614,8/5/1957,224.2,69,33.1
13,14,female,Anenechi,Chidi,826 Broad Street,Birmingham,AL,35203.0,United States,AnenechiChidi@armyspy.com+1 (205) 417-8095,3/7/1961,228.4,67,35.8
14,15,female,Asia,WoÅºniak,4970 Heather Sees Way,Tulsa,OK,74105.0,United States,AsiaWozniak@rhyta.com918-712-3469,8/15/1997,112.0,65,18.6
15,16,male,SÃ¸ren,Lund,2438 Shady Pines Drive,Kingsport,VA,37660.0,United States,276-225-1955SrenFLund@gustr.com,8/23/1922,201.5,64,34.6
16,17,female,TÃ¡m,Liá» u,2152 Heritage Road,Fresno,California,93706.0,United States,LieuThiThuTam@dayrep.com1 559 765 7836,11/14/1952,183.9,61,34.7
17,18,female,Roxanne,Andreyeva,2103 Edington Drive,Smyrna,GA,30082.0,United States,RoxanneAndreyeva@armyspy.com678-829-8578,7/24/1922,129.1,60,25.2
18,19,male,William,Oates,441 Tibbs Avenue,Ekalaka,MT,59324.0,United States,406-775-2696WilliamVOates@armyspy.com,9/4/1949,202.2,64,34.7
19,20,male,Zak,Kelly,994 Hill Croft Farm Road,Oroville,California,95966.0,United States,ZakKelly@rhyta.com1 530 532 8397,12/13/1988,208.8,70,30.0
20,21,female,Sofia,Karlsen,2931 Romano Street,Whitman,MA,2382.0,United States,SofiaTKarlsen@teleworm.us1 781 447 1763,9/24/1934,153.1,66,24.7
21,22,male,SamÃºel,GuÃ°brandsson,1904 Granville Lane,Elmsford,NJ,10523.0,United States,973-445-5341SamuelGubrandsson@teleworm.us,4/12/1983,223.7,69,33.0
22,23,male,Manchu,Su,1092 Deans Lane,Pleasantville,NY,10570.0,United States,914-745-6108ManchuSu@einrot.com,1/19/1936,130.7,65,21.7
23,24,male,Lovre,GaliÄ,4941 Marion Drive,Winter Haven,Florida,33830.0,United States,LovreGalic@gustr.com1 813 355 9476,5/26/1960,222.9,66,36.0
24,25,male,Jakob,Jakobsen,648 Old Dear Lane,Port Jervis,New York,12771.0,United States,JakobCJakobsen@einrot.com+1 (845) 858-7707,8/1/1985,155.8,67,24.4
25,26,male,Gregor,Bole,922 Chapmans Lane,Albuquerque,NM,87109.0,United States,GregorBole@gustr.com505-828-4955,6/19/1922,180.8,67,28.3
26,27,female,Ella,Lund,1207 Garfield Road,Peoria,IL,61602.0,United States,309-671-8852EllaLund@armyspy.com,12/19/1933,144.8,61,27.4
27,28,male,Joseph,Tucker,4982 Wood Street,Venice,LA,70091.0,United States,985-814-7603JosephNTucker@rhyta.com,4/10/1959,175.8,72,23.8
28,29,male,Robert,Wolf,2386 Linda Street,Fort Washington,PA,19034.0,United States,RobertWolf@fleckens.hu1 267 895 7462,6/26/1937,206.6,70,29.6
29,30,male,Jake,Jakobsen,648 Old Dear Lane,Port Jervis,New York,12771.0,United States,JakobCJakobsen@einrot.com+1 (845) 858-7707,8/1/1985,155.8,67,24.4
30,31,female,Janina,Bazarova,3259 Roy Alley,Englewood,CO,80112.0,United States,303-910-2058JaninaBazarova@superrito.com,6/29/1964,156.9,65,26.1
31,32,male,TomÃ¡Å¡,NavrÃ¡til,4870 Corbin Branch Road,Bluff City,TN,37618.0,United States,423-538-4887TomasNavratil@dayrep.com,4/8/1935,133.3,70,19.1
32,33,female,Má»t,Pháº¡m,2690 Pin Oak Drive,Long Beach,CA,90815.0,United States,PhamThiBichMot@dayrep.com562-985-4582,1/30/1997,147.6,69,21.8
33,34,male,Habte,Kifle,2055 Emeral Dreams Drive,Dekalb,Illinois,60115.0,United States,815-270-7770HabteKifle@fleckens.hu,1/20/1946,153.8,72,20.9
34,35,female,Mariana,Souza,577 Chipmunk Lane,Orrington,ME,4474.0,United States,207-825-8634MarianaGomesSouza@superrito.com,3/6/1948,152.9,63,27.1
35,36,female,Kamila,PecinovÃ¡,3558 Longview Avenue,New York,New York,10004.0,United States,718-501-0503KamilaPecinova@dayrep.com,12/23/1985,198.9,62,36.4
36,37,female,Naja,Enoksen,2915 Lynn Avenue,Eau Claire,WI,54701.0,United States,NajaEnoksen@fleckens.hu715-562-7013,11/26/1931,156.4,66,25.2
37,38,female,Albinca,Komavec,1257 Elsie Drive,Huron,SD,57350.0,United States,AlbincaKomavec@rhyta.com+1 (605) 204-6572,6/5/1986,189.9,66,30.6
38,39,female,Genet,Fesahaye,4649 Joanne Lane,Westborough,MA,1581.0,United States,GenetFesahaye@armyspy.com1 978 460 9060,1/11/1954,111.8,67,17.5
39,40,female,Ganimete,Å ÄanÄar,4105 Ferguson Street,Walpole,MA,2081.0,United States,508-454-2027GanimeteScancar@cuvox.de,10/25/1947,191.6,67,30.0

In [9]:
treatment

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrovÃ¡,41u - 48u,-,7.63,7.20,NaN
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.97
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32
...,...,...,...,...,...,...,...
275,albina,zetticci,45u - 51u,-,7.93,7.73,0.20
276,john,teichelmann,-,49u - 49u,7.90,7.58,NaN
277,mathea,lillebÃ¸,23u - 36u,-,9.04,8.67,0.37
278,vallie,prince,31u - 38u,-,7.64,7.28,0.36
279,samÃºel,guÃ°brandsson,53u - 56u,-,8.00,7.64,0.36

In [11]:
adversity

     given_name     surname           adverse_reaction
0         berta  napolitani  injection site discomfort
1          lena        baer               hypoglycemia
2        joseph         day               hypoglycemia
3        flavia  fiorentino                      cough
4       manouck     wubbels          throat irritation
5       jasmine       sykes               hypoglycemia
6        louise     johnson               hypoglycemia
7       albinca     komavec               hypoglycemia
8           noe      aranda               hypoglycemia
9         sofia   hermansen  injection site discomfort
10        tegan     johnson                   headache
11         abel     yonatan                      cough
12    abdul-nur         isa               hypoglycemia
13         leon      scholz  injection site discomfort
14     gabriele     saenger               hypoglycemia
15       jia li        teng                     nausea
16        jakob    jakobsen               hypoglycemia
17  christopher    woodward                     nausea
18          ole    petersen               hypoglycemia
19       finley    chandler                   headache
20     anenechi       chidi               hypoglycemia
21     miÅosÅaw  wiÅniewski  injection site discomfort
22        lixue       hsueh  injection site discomfort
23        merci      leroux               hypoglycemia
24         kang         mai  injection site discomfort
25       elliot  richardson               hypoglycemia
26      clinton      miller          throat irritation
27       idalia       moore               hypoglycemia
28       xiuxiu       chang               hypoglycemia
29         alex    crawford               hypoglycemia
30       monika      lonÄar               hypoglycemia
31       steven         roy                   headache
32      cecilie      nilsen               hypoglycemia
33    krisztina      magyar               hypoglycemia

## Two different datas need to be cleaned
 ####        Dirty data
 ####        Untidy data
 
 ### OBSERVATIONS:-

## Conclusions about:--

In [12]:
patients.columns

Index(['patient_id', 'assigned_sex', 'given_name', 'surname', 'address',
       'city', 'state', 'zip_code', 'country', 'contact', 'birthdate',
       'weight', 'height', 'bmi'],
      dtype='object')

In [13]:
patients[patients['address'].duplicated()]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
29,30,male,Jake,Jakobsen,648 Old Dear Lane,Port Jervis,New York,12771.0,United States,JakobCJakobsen@einrot.com+1 (845) 858-7707,8/1/1985,155.8,67,24.4
219,220,male,Má»¹,Quynh,NaN,NaN,NaN,NaN,NaN,NaN,4/9/1978,237.8,69,35.1
229,230,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
230,231,female,Elisabeth,Knudsen,NaN,NaN,NaN,NaN,NaN,NaN,9/23/1976,165.9,63,29.4
234,235,female,Martina,TomÃ¡nkovÃ¡,NaN,NaN,NaN,NaN,NaN,NaN,4/7/1936,199.5,65,33.2
237,238,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
242,243,male,John,O'Brian,NaN,NaN,NaN,NaN,NaN,NaN,2/25/1957,205.3,74,26.4
244,245,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
249,250,male,Benjamin,Mehler,NaN,NaN,NaN,NaN,NaN,NaN,10/30/1951,146.5,69,21.6
251,252,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
257,258,male,Jin,Kung,NaN,NaN,NaN,NaN,NaN,NaN,5/17/1995,231.7,69,34.2
264,265,female,Wafiyyah,Asfour,NaN,NaN,NaN,NaN,NaN,NaN,11/3/1989,158.6,63,28.1
269,270,female,Flavia,Fiorentino,NaN,NaN,NaN,NaN,NaN,NaN,10/9/1937,175.2,61,33.1
277,278,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
278,279,female,Generosa,CabÃ¡n,NaN,NaN,NaN,NaN,NaN,NaN,12/16/1962,124.3,69,18.4
282,283,female,Sandy,Taylor,2476 Fulton Street,Rainelle,WV,25962.0,United States,304-438-2648SandraCTaylor@dayrep.com,10/23/1960,206.1,64,35.4
286,287,male,Lewis,Webb,NaN,NaN,NaN,NaN,NaN,NaN,4/1/1979,155.3,68,23.6
296,297,female,Chá»,LÃ¢m,NaN,NaN,NaN,NaN,NaN,NaN,5/14/1990,181.1,63,32.1
502,503,male,Pat,Gersten,2778 North Avenue,Burr,Nebraska,68324.0,United States,PatrickGersten@rhyta.com402-848-4923,5/3/1954,138.2,71,19.3

In [14]:
patients

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,male,LiÃªm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,499,male,Mustafa,LindstrÃ¶m,2530 Victoria Court,Milton Mills,ME,3852.0,United States,207-477-0579MustafaLindstrom@jourrapide.com,4/10/1959,181.1,72,24.6
499,500,male,Ruman,Bisliev,494 Clarksburg Park Road,Sedona,AZ,86341.0,United States,928-284-4492RumanBisliev@gustr.com,3/26/1948,239.6,70,34.4
500,501,female,Jinke,de Keizer,649 Nutter Street,Overland Park,MO,64110.0,United States,816-223-6007JinkedeKeizer@teleworm.us,1/13/1971,171.2,67,26.8
501,502,female,Chidalu,Onyekaozulu,3652 Boone Crockett Lane,Seattle,WA,98109.0,United States,ChidaluOnyekaozulu@jourrapide.com1 360 443 2060,2/13/1952,176.9,67,27.7
502,503,male,Pat,Gersten,2778 North Avenue,Burr,Nebraska,68324.0,United States,PatrickGersten@rhyta.com402-848-4923,5/3/1954,138.2,71,19.3

## Patients
    - Extra col for indexing other than patient_id
    - state col has the abreviated as well as complete names (lack of consistency)
    - Zip_code in decimal && 4 digits or 5 digits -two types
    - Formatting of phone number os inconsistent
    - Email and phone number are in same col must be two diff cols
    - height shold be float not int
    - Missing vlaues in cols = (adress, contact, city, state, zip_code, country) // notjing can be done
    - Nan values from row (204 to 296)
    - addresss col has duplicates in name , surname, address which is not filled but not mked nan remain default
    - donot know about the weight parameter , height and bmi parameter

In [15]:
treatment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    280 non-null    object
 1   surname       280 non-null    object
 2   auralin       280 non-null    object
 3   novodra       280 non-null    object
 4   hba1c_start   280 non-null    float64
 5   hba1c_end     280 non-null    float64
 6   hba1c_change  171 non-null    float64
dtypes: float64(3), object(4)
memory usage: 15.4+ KB

## Treatment
    - Name and surname are not consistent with that in patients data
    - auralin novodra => lower_dose, upper_dose, name of drug need to be three cols (Nan values also reduced)
    - auralin novodra has the dash(-) which cannot be handled
    - hba1c_change is not calculated for some values also it is wrong also for some vaues
    - hba1c_change has nan values

In [16]:
adversity

     given_name     surname           adverse_reaction
0         berta  napolitani  injection site discomfort
1          lena        baer               hypoglycemia
2        joseph         day               hypoglycemia
3        flavia  fiorentino                      cough
4       manouck     wubbels          throat irritation
5       jasmine       sykes               hypoglycemia
6        louise     johnson               hypoglycemia
7       albinca     komavec               hypoglycemia
8           noe      aranda               hypoglycemia
9         sofia   hermansen  injection site discomfort
10        tegan     johnson                   headache
11         abel     yonatan                      cough
12    abdul-nur         isa               hypoglycemia
13         leon      scholz  injection site discomfort
14     gabriele     saenger               hypoglycemia
15       jia li        teng                     nausea
16        jakob    jakobsen               hypoglycemia
17  christopher    woodward                     nausea
18          ole    petersen               hypoglycemia
19       finley    chandler                   headache
20     anenechi       chidi               hypoglycemia
21     miÅosÅaw  wiÅniewski  injection site discomfort
22        lixue       hsueh  injection site discomfort
23        merci      leroux               hypoglycemia
24         kang         mai  injection site discomfort
25       elliot  richardson               hypoglycemia
26      clinton      miller          throat irritation
27       idalia       moore               hypoglycemia
28       xiuxiu       chang               hypoglycemia
29         alex    crawford               hypoglycemia
30       monika      lonÄar               hypoglycemia
31       steven         roy                   headache
32      cecilie      nilsen               hypoglycemia
33    krisztina      magyar               hypoglycemia

## Adverse_reactions
    - name and surname are not consistent with the data set name surname in patients
    - extra dataset is created to just tell the adverse effect of patient 
    - just add another col in the patient list only to handle this information

# Some key points

## -> try to convert the data into either catorical or the numercal data
## -> make the datset tidy to handle
## -> each row must contain oly one type of information
## -> handle the missing values
## -> Consistent dataset