In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
patients = pd.read_csv('patients.csv',index_col='patient_id')
treatment = pd.read_csv('treatments.csv')
adversity = pd.read_csv('adverse_reactions.csv')

In [3]:
p = patients.copy()
t = treatment.copy()
a = adversity.copy()

## Patients
    - state col has the abreviated as well as complete names (lack of consistency) => nothing cannot be done
    - Email and phone number are in same col must be two diff cols // Reamining => didnot able to do it

##  Missing vlaues in cols = (adress, contact, city, state, zip_code, country) // nothing can be done

In [4]:
# p.loc[(p['given_name'] == 'John') & (p['surname'] == 'Doe'), ['address']] = np.nan
# p.loc[(p['given_name'] == 'John') & (p['surname'] == 'Doe'), ['contact']] = np.nan
# p.loc[(p['given_name'] == 'John') & (p['surname'] == 'Doe'), ['city']] = np.nan
# p.loc[(p['given_name'] == 'John') & (p['surname'] == 'Doe'), ['birthdate']] = np.nan
# p.loc[(p['given_name'] == 'John') & (p['surname'] == 'Doe'), ['weight']] = np.nan
# p.loc[(p['given_name'] == 'John') & (p['surname'] == 'Doe'), ['height']] = np.nan
# p.loc[(p['given_name'] == 'John') & (p['surname'] == 'Doe'), ['country']] = np.nan
# p.loc[(p['given_name'] == 'John') & (p['surname'] == 'Doe'), ['zip_code']] = np.nan
# p.loc[(p['given_name'] == 'John') & (p['surname'] == 'Doe'), ['state']] = np.nan
# p.loc[(p['given_name'] == 'John') & (p['surname'] == 'Doe'), ['bmi']] = np.nan
# p.loc[(p['given_name'] == 'John') & (p['surname'] == 'Doe'), ['assigned_sex']] = np.nan


p.loc[(p['given_name'] == 'John') & (p['surname'] == 'Doe')] = np.nan

## - addresss col has duplicates in name , surname, address which is not filled but not maked nan remain default - make as nan 
## Dropped

In [5]:
p.loc[(p['given_name'] == 'John') & (p['surname'] == 'Doe')]
p.dropna(how='all', inplace=True)

In [6]:
p.info()

<class 'pandas.core.frame.DataFrame'>
Index: 497 entries, 1 to 503
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   assigned_sex  497 non-null    object
 1   given_name    497 non-null    object
 2   surname       497 non-null    object
 3   address       485 non-null    object
 4   city          485 non-null    object
 5   state         485 non-null    object
 6   zip_code      485 non-null    float64
 7   country       485 non-null    object
 8   contact       485 non-null    object
 9   birthdate     497 non-null    object
 10  weight        497 non-null    float64
 11  height        497 non-null    float64
 12  bmi           497 non-null    float64
dtypes: float64(4), object(9)
memory usage: 54.4+ KB

In [7]:
patients.head(50)

,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
patient_id,,,,,,,,,,,,,
1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
4,male,LiÃªm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1
6,male,Rafael,Costa,1140 Willis Avenue,Daytona Beach,Florida,32114.0,United States,386-334-5237RafaelCardosoCosta@gustr.com,8/31/1931,183.9,70,26.4
7,female,Mary,Adams,3145 Sheila Lane,Burbank,NV,84728.0,United States,775-533-5933MaryBAdams@einrot.com,11/19/1969,146.3,65,24.3
8,female,Xiuxiu,Chang,2687 Black Oak Hollow Road,Morgan Hill,CA,95037.0,United States,XiuxiuChang@einrot.com1 408 778 3236,8/13/1958,158.0,60,30.9
9,male,Dsvid,Gustafsson,1790 Nutter Street,Kansas City,MO,64105.0,United States,816-265-9578DavidGustafsson@armyspy.com,3/6/1937,163.9,66,26.5
10,female,Sophie,Cabrera,3303 Anmoore Road,New York,New York,10011.0,United States,SophieCabreraIbarra@teleworm.us1 718 795 9124,12/3/1930,194.7,64,33.4
11,female,Sandy,Gunnarsson,87 Wood Duck Drive,Rudyard,MI,49780.0,United States,906-478-8949SandyGunnarsson@dayrep.com,7/16/1974,199.3,62,36.4
12,male,Abdul-Nur,Isa,1092 Farm Meadow Drive,Brentwood,TN,37027.0,United States,Abdul-NurMummarIsa@rhyta.com1 931 207 0839,2/3/1954,238.7,73,31.5
13,male,Omeokachie,Ibeamaka,2544 Worley Avenue,Lynchburg,VA,24504.0,United States,OmeokachieIbeamaka@einrot.com434-509-2614,8/5/1957,224.2,69,33.1
14,female,Anenechi,Chidi,826 Broad Street,Birmingham,AL,35203.0,United States,AnenechiChidi@armyspy.com+1 (205) 417-8095,3/7/1961,228.4,67,35.8
15,female,Asia,WoÅºniak,4970 Heather Sees Way,Tulsa,OK,74105.0,United States,AsiaWozniak@rhyta.com918-712-3469,8/15/1997,112.0,65,18.6
16,male,SÃ¸ren,Lund,2438 Shady Pines Drive,Kingsport,VA,37660.0,United States,276-225-1955SrenFLund@gustr.com,8/23/1922,201.5,64,34.6
17,female,TÃ¡m,Liá» u,2152 Heritage Road,Fresno,California,93706.0,United States,LieuThiThuTam@dayrep.com1 559 765 7836,11/14/1952,183.9,61,34.7
18,female,Roxanne,Andreyeva,2103 Edington Drive,Smyrna,GA,30082.0,United States,RoxanneAndreyeva@armyspy.com678-829-8578,7/24/1922,129.1,60,25.2
19,male,William,Oates,441 Tibbs Avenue,Ekalaka,MT,59324.0,United States,406-775-2696WilliamVOates@armyspy.com,9/4/1949,202.2,64,34.7
20,male,Zak,Kelly,994 Hill Croft Farm Road,Oroville,California,95966.0,United States,ZakKelly@rhyta.com1 530 532 8397,12/13/1988,208.8,70,30.0
21,female,Sofia,Karlsen,2931 Romano Street,Whitman,MA,2382.0,United States,SofiaTKarlsen@teleworm.us1 781 447 1763,9/24/1934,153.1,66,24.7
22,male,SamÃºel,GuÃ°brandsson,1904 Granville Lane,Elmsford,NJ,10523.0,United States,973-445-5341SamuelGubrandsson@teleworm.us,4/12/1983,223.7,69,33.0
23,male,Manchu,Su,1092 Deans Lane,Pleasantville,NY,10570.0,United States,914-745-6108ManchuSu@einrot.com,1/19/1936,130.7,65,21.7
24,male,Lovre,GaliÄ,4941 Marion Drive,Winter Haven,Florida,33830.0,United States,LovreGalic@gustr.com1 813 355 9476,5/26/1960,222.9,66,36.0
25,male,Jakob,Jakobsen,648 Old Dear Lane,Port Jervis,New York,12771.0,United States,JakobCJakobsen@einrot.com+1 (845) 858-7707,8/1/1985,155.8,67,24.4
26,male,Gregor,Bole,922 Chapmans Lane,Albuquerque,NM,87109.0,United States,GregorBole@gustr.com505-828-4955,6/19/1922,180.8,67,28.3
27,female,Ella,Lund,1207 Garfield Road,Peoria,IL,61602.0,United States,309-671-8852EllaLund@armyspy.com,12/19/1933,144.8,61,27.4
28,male,Joseph,Tucker,4982 Wood Street,Venice,LA,70091.0,United States,985-814-7603JosephNTucker@rhyta.com,4/10/1959,175.8,72,23.8
29,male,Robert,Wolf,2386 Linda Street,Fort Washington,PA,19034.0,United States,RobertWolf@fleckens.hu1 267 895 7462,6/26/1937,206.6,70,29.6
30,male,Jake,Jakobsen,648 Old Dear Lane,Port Jervis,New York,12771.0,United States,JakobCJakobsen@einrot.com+1 (845) 858-7707,8/1/1985,155.8,67,24.4
31,female,Janina,Bazarova,3259 Roy Alley,Englewood,CO,80112.0,United States,303-910-2058JaninaBazarova@superrito.com,6/29/1964,156.9,65,26.1
32,male,TomÃ¡Å¡,NavrÃ¡til,4870 Corbin Branch Road,Bluff City,TN,37618.0,United States,423-538-4887TomasNavratil@dayrep.com,4/8/1935,133.3,70,19.1
33,female,Má»t,Pháº¡m,2690 Pin Oak Drive,Long Beach,CA,90815.0,United States,PhamThiBichMot@dayrep.com562-985-4582,1/30/1997,147.6,69,21.8
34,male,Habte,Kifle,2055 Emeral Dreams Drive,Dekalb,Illinois,60115.0,United States,815-270-7770HabteKifle@fleckens.hu,1/20/1946,153.8,72,20.9
35,female,Mariana,Souza,577 Chipmunk Lane,Orrington,ME,4474.0,United States,207-825-8634MarianaGomesSouza@superrito.com,3/6/1948,152.9,63,27.1
36,female,Kamila,PecinovÃ¡,3558 Longview Avenue,New York,New York,10004.0,United States,718-501-0503KamilaPecinova@dayrep.com,12/23/1985,198.9,62,36.4
37,female,Naja,Enoksen,2915 Lynn Avenue,Eau Claire,WI,54701.0,United States,NajaEnoksen@fleckens.hu715-562-7013,11/26/1931,156.4,66,25.2
38,female,Albinca,Komavec,1257 Elsie Drive,Huron,SD,57350.0,United States,AlbincaKomavec@rhyta.com+1 (605) 204-6572,6/5/1986,189.9,66,30.6
39,female,Genet,Fesahaye,4649 Joanne Lane,Westborough,MA,1581.0,United States,GenetFesahaye@armyspy.com1 978 460 9060,1/11/1954,111.8,67,17.5
40,female,Ganimete,Å ÄanÄar,4105 Ferguson Street,Walpole,MA,2081.0,United States,508-454-2027GanimeteScancar@cuvox.de,10/25/1947,191.6,67,30.0
41,male,TjeÅ¡imir,LukiÄ,3636 Junior Avenue,Atlanta,GA,30303.0,United States,TjesimirLukic@jourrapide.com1 404 547 4508,10/24/1941,147.8,70,21.2
42,male,Fakhri,Fakhoury,155 Red Hawk Road,Danube,MN,56230.0,United States,FakhriHaniFakhoury@cuvox.de320-826-3340,11/4/1979,143.0,66,23.1
43,female,Mizuki,Iwata,3434 Holt Street,West Palm Beach,FL,33409.0,United States,MizukiIwata@gustr.com561-357-0702,6/30/1927,199.1,61,37.6
44,female,Zizi,Schmitt,669 Archwood Avenue,Mountain View,WY,82939.0,United States,SchmittZizi@fleckens.hu1 307 712 0508,2/9/1968,198.9,67,31.1
45,female,Blanka,JurkoviÄ,3165 Upton Avenue,Waterville,ME,4901.0,United States,BlankaJurkovic@superrito.com1 207 861 4587,1/26/1923,129.8,66,20.9
46,female,Liisa,SeppÃ¤lÃ¤,1012 Lords Way,Adamsville,TN,38310.0,United States,LiisaSeppala@einrot.com1 731 632 2908,2/15/1930,157.7,63,27.9
47,male,Javier,Moquin,1808 Stuart Street,Pittsburgh,PA,15201.0,United States,724-419-3583JavierMoquin@rhyta.com,8/7/1941,163.9,72,22.2
48,female,Ana,Correia,1495 Post Farm Road,Atlanta,GA,30337.0,United States,404-289-1766AnaSousaCorreia@rhyta.com,11/4/1962,186.6,65,31.0
49,female,Annika,Vaara,4853 University Drive,Lombard,IL,60148.0,United States,AnnikaVaara@rhyta.com312-719-7238,2/20/1996,109.1,67,17.1
50,female,Vivien,ZsinkÃ³,4141 Davis Place,Maumee,OH,43537.0,United States,419-262-6953ZsinkoVivien@teleworm.us,3/6/1974,113.3,64,19.4

In [8]:
patients.info()

<class 'pandas.core.frame.DataFrame'>
Index: 503 entries, 1 to 503
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   assigned_sex  503 non-null    object
 1   given_name    503 non-null    object
 2   surname       503 non-null    object
 3   address       491 non-null    object
 4   city          491 non-null    object
 5   state         491 non-null    object
 6   zip_code      491 non-null    float64
 7   country       491 non-null    object
 8   contact       491 non-null    object
 9   birthdate     503 non-null    object
 10  weight        503 non-null    float64
 11  height        503 non-null    int64
 12  bmi           503 non-null    float64
dtypes: float64(3), int64(1), object(9)
memory usage: 55.0+ KB

# Email and phone_numbers seperated

In [9]:
p['phone_number'] = p.contact.str.extract('((?:\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4})', expand=True)

# [a-zA-Z] to signify emails in this dataset all start and end with letters
p['email'] = p.contact.str.extract('([a-zA-Z][a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+[a-zA-Z])', expand=True)

# Note: axis=1 denotes that we are referring to a column, not a row
p = p.drop('contact', axis=1)

In [10]:
p

,assigned_sex,given_name,surname,address,city,state,zip_code,country,birthdate,weight,height,bmi,phone_number,email
patient_id,,,,,,,,,,,,,,
1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,7/10/1976,121.7,66.0,19.6,951-719-9170,ZoeWellish@superrito.com
2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,4/3/1967,118.8,66.0,19.2,+1 (217) 569-3204,PamelaSHill@cuvox.de
3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,2/19/1980,177.8,71.0,24.8,402-363-6804,JaeMDebord@gustr.com
4,male,LiÃªm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,7/26/1951,220.9,70.0,31.7,+1 (732) 636-8246,PhanBaLiem@jourrapide.com
5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,2/18/1928,192.3,27.0,26.1,334-515-7487,TimNeudorf@cuvox.de
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,male,Mustafa,LindstrÃ¶m,2530 Victoria Court,Milton Mills,ME,3852.0,United States,4/10/1959,181.1,72.0,24.6,207-477-0579,MustafaLindstrom@jourrapide.com
500,male,Ruman,Bisliev,494 Clarksburg Park Road,Sedona,AZ,86341.0,United States,3/26/1948,239.6,70.0,34.4,928-284-4492,RumanBisliev@gustr.com
501,female,Jinke,de Keizer,649 Nutter Street,Overland Park,MO,64110.0,United States,1/13/1971,171.2,67.0,26.8,816-223-6007,JinkedeKeizer@teleworm.us
502,female,Chidalu,Onyekaozulu,3652 Boone Crockett Lane,Seattle,WA,98109.0,United States,2/13/1952,176.9,67.0,27.7,360 443 2060,ChidaluOnyekaozulu@jourrapide.com
503,male,Pat,Gersten,2778 North Avenue,Burr,Nebraska,68324.0,United States,5/3/1954,138.2,71.0,19.3,402-848-4923,PatrickGersten@rhyta.com

##     height should be float not int
### DONE

In [11]:
p['height'].astype('float')

patient_id
1      66.0
2      66.0
3      71.0
4      70.0
5      27.0
       ...
499    72.0
500    70.0
501    67.0
502    67.0
503    71.0
Name: height, Length: 497, dtype: float64

In [12]:
p.info()

<class 'pandas.core.frame.DataFrame'>
Index: 497 entries, 1 to 503
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   assigned_sex  497 non-null    object
 1   given_name    497 non-null    object
 2   surname       497 non-null    object
 3   address       485 non-null    object
 4   city          485 non-null    object
 5   state         485 non-null    object
 6   zip_code      485 non-null    float64
 7   country       485 non-null    object
 8   birthdate     497 non-null    object
 9   weight        497 non-null    float64
 10  height        497 non-null    float64
 11  bmi           497 non-null    float64
 12  phone_number  485 non-null    object
 13  email         485 non-null    object
dtypes: float64(4), object(10)
memory usage: 58.2+ KB

## Adverse_reactions
### name and surname are not consistent with the data set name surname in patients
### extra dataset is created to just tell the adverse effect of patient 
### just add another col in the patient list only to handle this informationDINE 
# DONE

In [14]:
a['given_name'] = a['given_name'].str.capitalize()
a['surname'] = a['surname'].str.capitalize()

In [15]:
p = pd.merge(p, a, on=['given_name', 'surname'], how='inner')

# zip_code type converted to string and make consistent with the data

In [16]:
p['zip_code'] = p['zip_code'].astype(str)

In [17]:
for index, value in p['zip_code'].items():
    if len(value) < 5:
        p.loc[index, 'zip_code'] = np.nan

In [18]:
p

,assigned_sex,given_name,surname,address,city,state,zip_code,country,birthdate,weight,height,bmi,phone_number,email,adverse_reaction
0,female,Xiuxiu,Chang,2687 Black Oak Hollow Road,Morgan Hill,CA,95037.0,United States,8/13/1958,158.0,60.0,30.9,408 778 3236,XiuxiuChang@einrot.com,hypoglycemia
1,female,Anenechi,Chidi,826 Broad Street,Birmingham,AL,35203.0,United States,3/7/1961,228.4,67.0,35.8,+1 (205) 417-8095,AnenechiChidi@armyspy.com,hypoglycemia
2,male,Jakob,Jakobsen,648 Old Dear Lane,Port Jervis,New York,12771.0,United States,8/1/1985,155.8,67.0,24.4,+1 (845) 858-7707,JakobCJakobsen@einrot.com,hypoglycemia
3,female,Albinca,Komavec,1257 Elsie Drive,Huron,SD,57350.0,United States,6/5/1986,189.9,66.0,30.6,+1 (605) 204-6572,AlbincaKomavec@rhyta.com,hypoglycemia
4,female,Noe,Aranda,3977 Jail Drive,Davenport,Illinois,52801.0,United States,8/7/1938,107.1,63.0,19.0,309 912 9553,NoeArandaGranado@dayrep.com,hypoglycemia
5,female,Louise,Johnson,4984 Hampton Meadows,Burlington,MA,1803.0,United States,3/1/1931,141.0,62.0,25.8,978-407-1874,LouiseJohnson@rhyta.com,hypoglycemia
6,male,Joseph,Day,1821 Virginia Street,Lombard,IL,60148.0,United States,2/23/1986,150.6,68.0,22.9,+1 (773) 615-9328,JosephMDay@teleworm.us,hypoglycemia
7,male,Elliot,Richardson,4230 Ridenour Street,Sunrise,FL,33323.0,United States,1/14/1973,168.1,71.0,23.4,786-234-0038,ElliotRichardson@teleworm.us,hypoglycemia
8,female,Lena,Baer,272 Boone Crockett Lane,Elma,WA,98541.0,United States,11/10/1977,170.7,61.0,32.2,360-482-2553,LenaBaer@rhyta.com,hypoglycemia
9,male,Finley,Chandler,2754 Westwood Avenue,New York,New York,10001.0,United States,10/25/1936,150.9,70.0,21.6,516-740-5280,FinleyChandler@dayrep.com,headache
10,male,Christopher,Woodward,3450 Southern Street,New York,NY,10004.0,United States,9/4/1984,212.2,66.0,34.2,+1 (516) 630-5900,ChristopherWoodward@jourrapide.com,nausea
11,female,Monika,LonÄar,377 Norman Street,Los Angeles,CA,90014.0,United States,7/19/1927,203.7,63.0,36.1,323-327-4721,MonikaLoncar@rhyta.com,hypoglycemia
12,female,Gabriele,Saenger,3499 Baker Avenue,Arlington,TX,76011.0,United States,8/26/1973,121.2,68.0,18.4,+1 (817) 909-5667,GabrieleSaenger@armyspy.com,hypoglycemia
13,female,Cecilie,Nilsen,1854 Kyle Street,North Loup,Nebraska,68859.0,United States,1/12/1950,181.3,64.0,31.1,308-496-7837,CecilieNilsen@superrito.com,hypoglycemia
14,female,Krisztina,Magyar,3820 Terry Lane,Orlando,Florida,32810.0,United States,5/3/1950,117.0,64.0,20.1,321-287-0484,MagyarKrisztina@superrito.com,hypoglycemia
15,male,Kang,Mai,1109 Beechwood Drive,Pittsburgh,PA,15205.0,United States,9/16/1986,200.4,70.0,28.8,412-274-6756,KangMai@jourrapide.com,injection site discomfort
16,male,Abel,Yonatan,2621 Koontz Lane,Burbank,California,91502.0,United States,4/29/1952,137.9,66.0,22.3,818 841 7660,AbelYonatan@teleworm.us,cough
17,female,Flavia,Fiorentino,NaN,NaN,NaN,NaN,NaN,10/9/1937,175.2,61.0,33.1,NaN,NaN,cough
18,male,Alex,Crawford,373 Fantages Way,Hope,ID,83836.0,United States,7/7/1924,223.1,70.0,32.0,+1 (208) 264-9063,AlexCrawford@dayrep.com,hypoglycemia
19,male,Leon,Scholz,3106 Evergreen Lane,Irvine,CA,92618.0,United States,9/14/1989,150.9,70.0,21.6,323 635 9919,LeonScholz@fleckens.hu,injection site discomfort
20,female,Lixue,Hsueh,1540 Overlook Drive,Crawfordsville,IN,47933.0,United States,3/29/1925,102.7,59.0,20.7,765-359-0147,LixueHsueh@dayrep.com,injection site discomfort
21,male,Ole,Petersen,3650 Graystone Lakes,Dudley,GA,31022.0,United States,7/14/1931,136.8,69.0,20.2,478-676-7058,OlePetersen@armyspy.com,hypoglycemia
22,female,Merci,Leroux,4519 Sussex Court,Copperas Cove,TX,76552.0,United States,6/8/1955,132.2,65.0,22.0,254-518-6365,MerciLeroux@jourrapide.com,hypoglycemia
23,male,MiÅosÅaw,WiÅniewski,796 Eagle Street,Collinsville,Illinois,62234.0,United States,11/13/1979,149.2,68.0,22.7,618-346-3914,MiloslawWisniewski@rhyta.com,injection site discomfort
24,female,Sofia,Hermansen,2272 Woodland Avenue,Houma,LA,70360.0,United States,2/27/1957,186.8,65.0,31.1,985-580-4827,SofiaBHermansen@rhyta.com,injection site discomfort
25,male,Steven,Roy,2816 Ashford Drive,Reston,VA,22070.0,United States,9/19/1975,162.4,72.0,22.0,703 716 8652,StevenBRoy@rhyta.com,headache
26,female,Manouck,Wubbels,4789 Devils Hill Road,Utica,MS,39175.0,United States,11/3/1964,201.5,65.0,33.5,601-885-6550,ManouckWubbels@armyspy.com,throat irritation
27,female,Tegan,Johnson,2636 Benson Park Drive,Oklahoma City,OK,73107.0,United States,1/19/1928,156.6,65.0,26.1,405-470-5088,TeganJohnson@gustr.com,headache
28,male,Clinton,Miller,901 Southern Street,Roslyn,NY,11576.0,United States,8/16/1985,195.4,74.0,25.1,516-626-8021,ClintonKMiller@rhyta.com,throat irritation
29,female,Idalia,Moore,4380 Grim Avenue,San Diego,California,92073.0,United States,10/26/1993,102.1,61.0,19.3,619-710-6286,IdaliaEMoore@cuvox.de,hypoglycemia
30,female,Berta,Napolitani,1815 Garrett Street,Philadelphia,PA,19108.0,United States,12/2/1958,153.3,63.0,27.2,267-972-3749,BertaNapolitani@rhyta.com,injection site discomfort
31,female,Jasmine,Sykes,2607 Water Street,Lafayette,California,94549.0,United States,12/1/1988,187.2,63.0,33.2,925-283-5425,JasmineSykes@jourrapide.com,hypoglycemia

In [19]:
p.loc[[5],['zip_code'] ] = np.nan

In [20]:
p.tail(50)

,assigned_sex,given_name,surname,address,city,state,zip_code,country,birthdate,weight,height,bmi,phone_number,email,adverse_reaction
0,female,Xiuxiu,Chang,2687 Black Oak Hollow Road,Morgan Hill,CA,95037.0,United States,8/13/1958,158.0,60.0,30.9,408 778 3236,XiuxiuChang@einrot.com,hypoglycemia
1,female,Anenechi,Chidi,826 Broad Street,Birmingham,AL,35203.0,United States,3/7/1961,228.4,67.0,35.8,+1 (205) 417-8095,AnenechiChidi@armyspy.com,hypoglycemia
2,male,Jakob,Jakobsen,648 Old Dear Lane,Port Jervis,New York,12771.0,United States,8/1/1985,155.8,67.0,24.4,+1 (845) 858-7707,JakobCJakobsen@einrot.com,hypoglycemia
3,female,Albinca,Komavec,1257 Elsie Drive,Huron,SD,57350.0,United States,6/5/1986,189.9,66.0,30.6,+1 (605) 204-6572,AlbincaKomavec@rhyta.com,hypoglycemia
4,female,Noe,Aranda,3977 Jail Drive,Davenport,Illinois,52801.0,United States,8/7/1938,107.1,63.0,19.0,309 912 9553,NoeArandaGranado@dayrep.com,hypoglycemia
5,female,Louise,Johnson,4984 Hampton Meadows,Burlington,MA,NaN,United States,3/1/1931,141.0,62.0,25.8,978-407-1874,LouiseJohnson@rhyta.com,hypoglycemia
6,male,Joseph,Day,1821 Virginia Street,Lombard,IL,60148.0,United States,2/23/1986,150.6,68.0,22.9,+1 (773) 615-9328,JosephMDay@teleworm.us,hypoglycemia
7,male,Elliot,Richardson,4230 Ridenour Street,Sunrise,FL,33323.0,United States,1/14/1973,168.1,71.0,23.4,786-234-0038,ElliotRichardson@teleworm.us,hypoglycemia
8,female,Lena,Baer,272 Boone Crockett Lane,Elma,WA,98541.0,United States,11/10/1977,170.7,61.0,32.2,360-482-2553,LenaBaer@rhyta.com,hypoglycemia
9,male,Finley,Chandler,2754 Westwood Avenue,New York,New York,10001.0,United States,10/25/1936,150.9,70.0,21.6,516-740-5280,FinleyChandler@dayrep.com,headache
10,male,Christopher,Woodward,3450 Southern Street,New York,NY,10004.0,United States,9/4/1984,212.2,66.0,34.2,+1 (516) 630-5900,ChristopherWoodward@jourrapide.com,nausea
11,female,Monika,LonÄar,377 Norman Street,Los Angeles,CA,90014.0,United States,7/19/1927,203.7,63.0,36.1,323-327-4721,MonikaLoncar@rhyta.com,hypoglycemia
12,female,Gabriele,Saenger,3499 Baker Avenue,Arlington,TX,76011.0,United States,8/26/1973,121.2,68.0,18.4,+1 (817) 909-5667,GabrieleSaenger@armyspy.com,hypoglycemia
13,female,Cecilie,Nilsen,1854 Kyle Street,North Loup,Nebraska,68859.0,United States,1/12/1950,181.3,64.0,31.1,308-496-7837,CecilieNilsen@superrito.com,hypoglycemia
14,female,Krisztina,Magyar,3820 Terry Lane,Orlando,Florida,32810.0,United States,5/3/1950,117.0,64.0,20.1,321-287-0484,MagyarKrisztina@superrito.com,hypoglycemia
15,male,Kang,Mai,1109 Beechwood Drive,Pittsburgh,PA,15205.0,United States,9/16/1986,200.4,70.0,28.8,412-274-6756,KangMai@jourrapide.com,injection site discomfort
16,male,Abel,Yonatan,2621 Koontz Lane,Burbank,California,91502.0,United States,4/29/1952,137.9,66.0,22.3,818 841 7660,AbelYonatan@teleworm.us,cough
17,female,Flavia,Fiorentino,NaN,NaN,NaN,NaN,NaN,10/9/1937,175.2,61.0,33.1,NaN,NaN,cough
18,male,Alex,Crawford,373 Fantages Way,Hope,ID,83836.0,United States,7/7/1924,223.1,70.0,32.0,+1 (208) 264-9063,AlexCrawford@dayrep.com,hypoglycemia
19,male,Leon,Scholz,3106 Evergreen Lane,Irvine,CA,92618.0,United States,9/14/1989,150.9,70.0,21.6,323 635 9919,LeonScholz@fleckens.hu,injection site discomfort
20,female,Lixue,Hsueh,1540 Overlook Drive,Crawfordsville,IN,47933.0,United States,3/29/1925,102.7,59.0,20.7,765-359-0147,LixueHsueh@dayrep.com,injection site discomfort
21,male,Ole,Petersen,3650 Graystone Lakes,Dudley,GA,31022.0,United States,7/14/1931,136.8,69.0,20.2,478-676-7058,OlePetersen@armyspy.com,hypoglycemia
22,female,Merci,Leroux,4519 Sussex Court,Copperas Cove,TX,76552.0,United States,6/8/1955,132.2,65.0,22.0,254-518-6365,MerciLeroux@jourrapide.com,hypoglycemia
23,male,MiÅosÅaw,WiÅniewski,796 Eagle Street,Collinsville,Illinois,62234.0,United States,11/13/1979,149.2,68.0,22.7,618-346-3914,MiloslawWisniewski@rhyta.com,injection site discomfort
24,female,Sofia,Hermansen,2272 Woodland Avenue,Houma,LA,70360.0,United States,2/27/1957,186.8,65.0,31.1,985-580-4827,SofiaBHermansen@rhyta.com,injection site discomfort
25,male,Steven,Roy,2816 Ashford Drive,Reston,VA,22070.0,United States,9/19/1975,162.4,72.0,22.0,703 716 8652,StevenBRoy@rhyta.com,headache
26,female,Manouck,Wubbels,4789 Devils Hill Road,Utica,MS,39175.0,United States,11/3/1964,201.5,65.0,33.5,601-885-6550,ManouckWubbels@armyspy.com,throat irritation
27,female,Tegan,Johnson,2636 Benson Park Drive,Oklahoma City,OK,73107.0,United States,1/19/1928,156.6,65.0,26.1,405-470-5088,TeganJohnson@gustr.com,headache
28,male,Clinton,Miller,901 Southern Street,Roslyn,NY,11576.0,United States,8/16/1985,195.4,74.0,25.1,516-626-8021,ClintonKMiller@rhyta.com,throat irritation
29,female,Idalia,Moore,4380 Grim Avenue,San Diego,California,92073.0,United States,10/26/1993,102.1,61.0,19.3,619-710-6286,IdaliaEMoore@cuvox.de,hypoglycemia
30,female,Berta,Napolitani,1815 Garrett Street,Philadelphia,PA,19108.0,United States,12/2/1958,153.3,63.0,27.2,267-972-3749,BertaNapolitani@rhyta.com,injection site discomfort
31,female,Jasmine,Sykes,2607 Water Street,Lafayette,California,94549.0,United States,12/1/1988,187.2,63.0,33.2,925-283-5425,JasmineSykes@jourrapide.com,hypoglycemia

## Treatment

In [21]:
t

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrovÃ¡,41u - 48u,-,7.63,7.20,NaN
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.97
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32
...,...,...,...,...,...,...,...
275,albina,zetticci,45u - 51u,-,7.93,7.73,0.20
276,john,teichelmann,-,49u - 49u,7.90,7.58,NaN
277,mathea,lillebÃ¸,23u - 36u,-,9.04,8.67,0.37
278,vallie,prince,31u - 38u,-,7.64,7.28,0.36
279,samÃºel,guÃ°brandsson,53u - 56u,-,8.00,7.64,0.36

##  Name and surname are now consistent with that in patients data

In [22]:
t['given_name'] = t['given_name'].str.capitalize()
t['surname'] = t['surname'].str.capitalize()

In [23]:
t

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,Veronika,JindrovÃ¡,41u - 48u,-,7.63,7.20,NaN
1,Elliot,Richardson,-,40u - 45u,7.56,7.09,0.97
2,Yukitaka,Takenaka,-,39u - 36u,7.68,7.25,NaN
3,Skye,Gormanston,33u - 36u,-,7.97,7.62,0.35
4,Alissa,Montez,-,33u - 29u,7.78,7.46,0.32
...,...,...,...,...,...,...,...
275,Albina,Zetticci,45u - 51u,-,7.93,7.73,0.20
276,John,Teichelmann,-,49u - 49u,7.90,7.58,NaN
277,Mathea,LillebÃ¸,23u - 36u,-,9.04,8.67,0.37
278,Vallie,Prince,31u - 38u,-,7.64,7.28,0.36
279,SamÃºel,GuÃ°brandsson,53u - 56u,-,8.00,7.64,0.36

## hba1c_change is not calculated for some values also it is wrong also for some vaues
## hba1c_change has nan values
# solved

In [24]:
t['hba1c_change'] = t['hba1c_start'] - t['hba1c_end']

### auralin novodra => lower_dose, upper_dose, name of drug need to be three cols (Nan values also reduced)
### auralin novodra has the dash(-) which cannot be handled
## Solved

In [25]:
drug_name = []
for i in t['auralin']:
    if i == '-':
        drug_name.append('novodra')
    else:
        drug_name.append('auralin')

In [26]:
t['drug_name']= drug_name  # need to drop the columns auralin and novadra but after seperating the string in them

In [27]:
value = 'auralin' # donot know about this error
upper_dose = []
lower_dose = []

j = 0
for i in range(560):
    drug = t.loc[[j], [value]].iloc[0, 0]
    if drug == '-':
        if value == 'novodra':
            value = 'auralin'
        else:
            value = 'novodra'
    else:
        parts = drug.split(' - ')
        lower_dose.append(parts[0])
        upper_dose.append(parts[1])
        j += 1

KeyError: "None of [Index([280], dtype='int32')] are in the [index]"

In [28]:
t['lower_dose'] = lower_dose
t['upper_dose'] = upper_dose

In [29]:
t.head(60)

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change,drug_name,lower_dose,upper_dose
0,Veronika,JindrovÃ¡,41u - 48u,-,7.63,7.20,0.43,auralin,41u,48u
1,Elliot,Richardson,-,40u - 45u,7.56,7.09,0.47,novodra,40u,45u
2,Yukitaka,Takenaka,-,39u - 36u,7.68,7.25,0.43,novodra,39u,36u
3,Skye,Gormanston,33u - 36u,-,7.97,7.62,0.35,auralin,33u,36u
4,Alissa,Montez,-,33u - 29u,7.78,7.46,0.32,novodra,33u,29u
5,Jasmine,Sykes,-,42u - 44u,7.56,7.18,0.38,novodra,42u,44u
6,Sophia,Haugen,37u - 42u,-,7.65,7.27,0.38,auralin,37u,42u
7,Eddie,Archer,31u - 38u,-,7.89,7.55,0.34,auralin,31u,38u
8,Saber,MÃ©nard,-,54u - 54u,8.08,7.70,0.38,novodra,54u,54u
9,Asia,WoÅºniak,30u - 36u,-,7.76,7.37,0.39,auralin,30u,36u
10,Joseph,Day,29u - 36u,-,7.70,7.19,0.51,auralin,29u,36u
11,Kristiina,HyypiÃ¤,-,36u - 38u,7.87,7.49,0.38,novodra,36u,38u
12,Roxanne,Andreyeva,29u - 38u,-,9.54,9.14,0.40,auralin,29u,38u
13,Gregor,Bole,-,47u - 45u,7.61,7.16,0.45,novodra,47u,45u
14,Simone,Baumgaertner,27u - 37u,-,7.74,7.30,0.44,auralin,27u,37u
15,Enco,Å½ibrik,55u - 68u,-,7.78,7.34,0.44,auralin,55u,68u
16,Camilla,Zaitseva,28u - 37u,-,7.53,7.13,0.40,auralin,28u,37u
17,Gina,Cain,-,36u - 36u,7.88,7.40,0.48,novodra,36u,36u
18,Addolorata,Lombardi,-,49u - 46u,7.75,7.33,0.42,novodra,49u,46u
19,Khalid,Johnsrud,-,54u - 54u,8.35,7.94,0.41,novodra,54u,54u
20,Mile,StaniÄ,-,47u - 48u,7.66,7.24,0.42,novodra,47u,48u
21,Tekla,Walczak,29u - 39u,-,7.61,7.29,0.32,auralin,29u,39u
22,Brancaleone,Russo,53u - 60u,-,8.61,8.18,0.43,auralin,53u,60u
23,Chiemela,Tobeolisa,-,43u - 47u,7.59,7.17,0.42,novodra,43u,47u
24,Isac,Berg,31u - 41u,-,9.68,9.29,0.39,auralin,31u,41u
25,BenoÃ®t,Bonami,-,44u - 43u,9.82,9.40,0.42,novodra,44u,43u
26,Suhaim,Rahal,-,49u - 47u,7.94,7.50,0.44,novodra,49u,47u
27,Mizuki,Iwata,-,45u - 46u,7.70,7.23,0.47,novodra,45u,46u
28,Clinton,Miller,42u - 51u,-,7.79,7.40,0.39,auralin,42u,51u
29,Eugene,Mironov,42u - 49u,-,7.81,7.48,0.33,auralin,42u,49u
30,Szilveszter,Totth,35u - 39u,-,7.70,7.38,0.32,auralin,35u,39u
31,Bao,She,-,48u - 45u,9.09,8.62,0.47,novodra,48u,45u
32,Laura,Ehrlichmann,-,43u - 40u,7.95,7.46,0.49,novodra,43u,40u
33,Cannan,Cabrera,-,40u - 31u,7.94,7.58,0.36,novodra,40u,31u
34,Alexander,Mathiesen,47u - 58u,-,7.96,7.55,0.41,auralin,47u,58u
35,Csaba,SÃ¡gi,-,35u - 29u,7.88,7.48,0.40,novodra,35u,29u
36,Chá»,LÃ¢m,45u - 48u,-,7.68,7.24,0.44,auralin,45u,48u
37,WÅadysÅaw,Wieczorek,24u - 37u,-,7.92,7.47,0.45,auralin,24u,37u
38,KristjÃ¡n,Ingason,44u - 55u,-,7.92,7.57,0.35,auralin,44u,55u
39,Krisztina,Magyar,-,32u - 27u,7.52,7.01,0.51,novodra,32u,27u
40,Ãsta,GrÃ­msdÃ³ttir,-,29u - 30u,7.62,7.16,0.46,novodra,29u,30u
41,Mahmud,Kadyrov,-,44u - 43u,7.53,7.11,0.42,novodra,44u,43u
42,Marija,GrubiÅ¡iÄ,37u - 43u,-,7.53,7.15,0.38,auralin,37u,43u
43,Jens,Poulsen,-,36u - 32u,7.55,7.16,0.39,novodra,36u,32u
44,Sauli,Koivuniemi,43u - 47u,-,7.67,7.37,0.30,auralin,43u,47u
45,ZdenÄk,Synek,-,31u - 31u,7.67,7.32,0.35,novodra,31u,31u
46,Mariana,Souza,36u - 42u,-,7.86,7.51,0.35,auralin,36u,42u
47,Jad allah,Gaber,-,38u - 41u,7.97,7.52,0.45,novodra,38u,41u
48,Zak,Kelly,-,38u - 38u,7.66,7.26,0.40,novodra,38u,38u
49,Jackson,Addison,-,42u - 42u,7.99,7.51,0.48,novodra,42u,42u
50,Albinca,Komavec,-,41u - 39u,7.89,7.46,0.43,novodra,41u,39u
51,Kristoffer,Martinsen,29u - 37u,-,9.18,8.64,0.54,auralin,29u,37u
52,Má»¹,Quynh,57u - 64u,-,7.61,7.16,0.45,auralin,57u,64u
53,Nasser,Mansour,-,33u - 31u,7.51,7.06,0.45,novodra,33u,31u
54,Oles,Zhdanov,54u - 67u,-,7.52,7.11,0.41,auralin,54u,67u
55,Triana.,Terrazas,34u - 42u,-,7.71,7.34,0.37,auralin,34u,42u
56,Juliusz,Majewski,-,41u - 39u,7.78,7.31,0.47,novodra,41u,39u
57,Klementyna,SokoÅowska,-,42u - 41u,7.98,7.53,0.45,novodra,42u,41u
58,GabryÅ,Tomaszewski,29u - 37u,-,7.87,7.47,0.40,auralin,29u,37u
59,Leixandre,Alanis,61u - 67u,-,7.74,7.32,0.42,auralin,61u,67u

In [35]:
t.drop(columns =['auralin', 'novodra'], inplace = True)

# CLEANED DATASETS

## PATIENTS || ADVERSE_REACTIONS COMBINED

In [31]:
p.head(60)

,assigned_sex,given_name,surname,address,city,state,zip_code,country,birthdate,weight,height,bmi,phone_number,email,adverse_reaction
0,female,Xiuxiu,Chang,2687 Black Oak Hollow Road,Morgan Hill,CA,95037.0,United States,8/13/1958,158.0,60.0,30.9,408 778 3236,XiuxiuChang@einrot.com,hypoglycemia
1,female,Anenechi,Chidi,826 Broad Street,Birmingham,AL,35203.0,United States,3/7/1961,228.4,67.0,35.8,+1 (205) 417-8095,AnenechiChidi@armyspy.com,hypoglycemia
2,male,Jakob,Jakobsen,648 Old Dear Lane,Port Jervis,New York,12771.0,United States,8/1/1985,155.8,67.0,24.4,+1 (845) 858-7707,JakobCJakobsen@einrot.com,hypoglycemia
3,female,Albinca,Komavec,1257 Elsie Drive,Huron,SD,57350.0,United States,6/5/1986,189.9,66.0,30.6,+1 (605) 204-6572,AlbincaKomavec@rhyta.com,hypoglycemia
4,female,Noe,Aranda,3977 Jail Drive,Davenport,Illinois,52801.0,United States,8/7/1938,107.1,63.0,19.0,309 912 9553,NoeArandaGranado@dayrep.com,hypoglycemia
5,female,Louise,Johnson,4984 Hampton Meadows,Burlington,MA,NaN,United States,3/1/1931,141.0,62.0,25.8,978-407-1874,LouiseJohnson@rhyta.com,hypoglycemia
6,male,Joseph,Day,1821 Virginia Street,Lombard,IL,60148.0,United States,2/23/1986,150.6,68.0,22.9,+1 (773) 615-9328,JosephMDay@teleworm.us,hypoglycemia
7,male,Elliot,Richardson,4230 Ridenour Street,Sunrise,FL,33323.0,United States,1/14/1973,168.1,71.0,23.4,786-234-0038,ElliotRichardson@teleworm.us,hypoglycemia
8,female,Lena,Baer,272 Boone Crockett Lane,Elma,WA,98541.0,United States,11/10/1977,170.7,61.0,32.2,360-482-2553,LenaBaer@rhyta.com,hypoglycemia
9,male,Finley,Chandler,2754 Westwood Avenue,New York,New York,10001.0,United States,10/25/1936,150.9,70.0,21.6,516-740-5280,FinleyChandler@dayrep.com,headache
10,male,Christopher,Woodward,3450 Southern Street,New York,NY,10004.0,United States,9/4/1984,212.2,66.0,34.2,+1 (516) 630-5900,ChristopherWoodward@jourrapide.com,nausea
11,female,Monika,LonÄar,377 Norman Street,Los Angeles,CA,90014.0,United States,7/19/1927,203.7,63.0,36.1,323-327-4721,MonikaLoncar@rhyta.com,hypoglycemia
12,female,Gabriele,Saenger,3499 Baker Avenue,Arlington,TX,76011.0,United States,8/26/1973,121.2,68.0,18.4,+1 (817) 909-5667,GabrieleSaenger@armyspy.com,hypoglycemia
13,female,Cecilie,Nilsen,1854 Kyle Street,North Loup,Nebraska,68859.0,United States,1/12/1950,181.3,64.0,31.1,308-496-7837,CecilieNilsen@superrito.com,hypoglycemia
14,female,Krisztina,Magyar,3820 Terry Lane,Orlando,Florida,32810.0,United States,5/3/1950,117.0,64.0,20.1,321-287-0484,MagyarKrisztina@superrito.com,hypoglycemia
15,male,Kang,Mai,1109 Beechwood Drive,Pittsburgh,PA,15205.0,United States,9/16/1986,200.4,70.0,28.8,412-274-6756,KangMai@jourrapide.com,injection site discomfort
16,male,Abel,Yonatan,2621 Koontz Lane,Burbank,California,91502.0,United States,4/29/1952,137.9,66.0,22.3,818 841 7660,AbelYonatan@teleworm.us,cough
17,female,Flavia,Fiorentino,NaN,NaN,NaN,NaN,NaN,10/9/1937,175.2,61.0,33.1,NaN,NaN,cough
18,male,Alex,Crawford,373 Fantages Way,Hope,ID,83836.0,United States,7/7/1924,223.1,70.0,32.0,+1 (208) 264-9063,AlexCrawford@dayrep.com,hypoglycemia
19,male,Leon,Scholz,3106 Evergreen Lane,Irvine,CA,92618.0,United States,9/14/1989,150.9,70.0,21.6,323 635 9919,LeonScholz@fleckens.hu,injection site discomfort
20,female,Lixue,Hsueh,1540 Overlook Drive,Crawfordsville,IN,47933.0,United States,3/29/1925,102.7,59.0,20.7,765-359-0147,LixueHsueh@dayrep.com,injection site discomfort
21,male,Ole,Petersen,3650 Graystone Lakes,Dudley,GA,31022.0,United States,7/14/1931,136.8,69.0,20.2,478-676-7058,OlePetersen@armyspy.com,hypoglycemia
22,female,Merci,Leroux,4519 Sussex Court,Copperas Cove,TX,76552.0,United States,6/8/1955,132.2,65.0,22.0,254-518-6365,MerciLeroux@jourrapide.com,hypoglycemia
23,male,MiÅosÅaw,WiÅniewski,796 Eagle Street,Collinsville,Illinois,62234.0,United States,11/13/1979,149.2,68.0,22.7,618-346-3914,MiloslawWisniewski@rhyta.com,injection site discomfort
24,female,Sofia,Hermansen,2272 Woodland Avenue,Houma,LA,70360.0,United States,2/27/1957,186.8,65.0,31.1,985-580-4827,SofiaBHermansen@rhyta.com,injection site discomfort
25,male,Steven,Roy,2816 Ashford Drive,Reston,VA,22070.0,United States,9/19/1975,162.4,72.0,22.0,703 716 8652,StevenBRoy@rhyta.com,headache
26,female,Manouck,Wubbels,4789 Devils Hill Road,Utica,MS,39175.0,United States,11/3/1964,201.5,65.0,33.5,601-885-6550,ManouckWubbels@armyspy.com,throat irritation
27,female,Tegan,Johnson,2636 Benson Park Drive,Oklahoma City,OK,73107.0,United States,1/19/1928,156.6,65.0,26.1,405-470-5088,TeganJohnson@gustr.com,headache
28,male,Clinton,Miller,901 Southern Street,Roslyn,NY,11576.0,United States,8/16/1985,195.4,74.0,25.1,516-626-8021,ClintonKMiller@rhyta.com,throat irritation
29,female,Idalia,Moore,4380 Grim Avenue,San Diego,California,92073.0,United States,10/26/1993,102.1,61.0,19.3,619-710-6286,IdaliaEMoore@cuvox.de,hypoglycemia
30,female,Berta,Napolitani,1815 Garrett Street,Philadelphia,PA,19108.0,United States,12/2/1958,153.3,63.0,27.2,267-972-3749,BertaNapolitani@rhyta.com,injection site discomfort
31,female,Jasmine,Sykes,2607 Water Street,Lafayette,California,94549.0,United States,12/1/1988,187.2,63.0,33.2,925-283-5425,JasmineSykes@jourrapide.com,hypoglycemia

In [32]:
p[(p['given_name'] == 'John')& (p['surname'] == 'Doe')]

Empty DataFrame
Columns: [assigned_sex, given_name, surname, address, city, state, zip_code, country, birthdate, weight, height, bmi, phone_number, email, adverse_reaction]
Index: []

## TREATMENT

In [36]:
t.head(60)

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,drug_name,lower_dose,upper_dose
0,Veronika,JindrovÃ¡,7.63,7.20,0.43,auralin,41u,48u
1,Elliot,Richardson,7.56,7.09,0.47,novodra,40u,45u
2,Yukitaka,Takenaka,7.68,7.25,0.43,novodra,39u,36u
3,Skye,Gormanston,7.97,7.62,0.35,auralin,33u,36u
4,Alissa,Montez,7.78,7.46,0.32,novodra,33u,29u
5,Jasmine,Sykes,7.56,7.18,0.38,novodra,42u,44u
6,Sophia,Haugen,7.65,7.27,0.38,auralin,37u,42u
7,Eddie,Archer,7.89,7.55,0.34,auralin,31u,38u
8,Saber,MÃ©nard,8.08,7.70,0.38,novodra,54u,54u
9,Asia,WoÅºniak,7.76,7.37,0.39,auralin,30u,36u
10,Joseph,Day,7.70,7.19,0.51,auralin,29u,36u
11,Kristiina,HyypiÃ¤,7.87,7.49,0.38,novodra,36u,38u
12,Roxanne,Andreyeva,9.54,9.14,0.40,auralin,29u,38u
13,Gregor,Bole,7.61,7.16,0.45,novodra,47u,45u
14,Simone,Baumgaertner,7.74,7.30,0.44,auralin,27u,37u
15,Enco,Å½ibrik,7.78,7.34,0.44,auralin,55u,68u
16,Camilla,Zaitseva,7.53,7.13,0.40,auralin,28u,37u
17,Gina,Cain,7.88,7.40,0.48,novodra,36u,36u
18,Addolorata,Lombardi,7.75,7.33,0.42,novodra,49u,46u
19,Khalid,Johnsrud,8.35,7.94,0.41,novodra,54u,54u
20,Mile,StaniÄ,7.66,7.24,0.42,novodra,47u,48u
21,Tekla,Walczak,7.61,7.29,0.32,auralin,29u,39u
22,Brancaleone,Russo,8.61,8.18,0.43,auralin,53u,60u
23,Chiemela,Tobeolisa,7.59,7.17,0.42,novodra,43u,47u
24,Isac,Berg,9.68,9.29,0.39,auralin,31u,41u
25,BenoÃ®t,Bonami,9.82,9.40,0.42,novodra,44u,43u
26,Suhaim,Rahal,7.94,7.50,0.44,novodra,49u,47u
27,Mizuki,Iwata,7.70,7.23,0.47,novodra,45u,46u
28,Clinton,Miller,7.79,7.40,0.39,auralin,42u,51u
29,Eugene,Mironov,7.81,7.48,0.33,auralin,42u,49u
30,Szilveszter,Totth,7.70,7.38,0.32,auralin,35u,39u
31,Bao,She,9.09,8.62,0.47,novodra,48u,45u
32,Laura,Ehrlichmann,7.95,7.46,0.49,novodra,43u,40u
33,Cannan,Cabrera,7.94,7.58,0.36,novodra,40u,31u
34,Alexander,Mathiesen,7.96,7.55,0.41,auralin,47u,58u
35,Csaba,SÃ¡gi,7.88,7.48,0.40,novodra,35u,29u
36,Chá»,LÃ¢m,7.68,7.24,0.44,auralin,45u,48u
37,WÅadysÅaw,Wieczorek,7.92,7.47,0.45,auralin,24u,37u
38,KristjÃ¡n,Ingason,7.92,7.57,0.35,auralin,44u,55u
39,Krisztina,Magyar,7.52,7.01,0.51,novodra,32u,27u
40,Ãsta,GrÃ­msdÃ³ttir,7.62,7.16,0.46,novodra,29u,30u
41,Mahmud,Kadyrov,7.53,7.11,0.42,novodra,44u,43u
42,Marija,GrubiÅ¡iÄ,7.53,7.15,0.38,auralin,37u,43u
43,Jens,Poulsen,7.55,7.16,0.39,novodra,36u,32u
44,Sauli,Koivuniemi,7.67,7.37,0.30,auralin,43u,47u
45,ZdenÄk,Synek,7.67,7.32,0.35,novodra,31u,31u
46,Mariana,Souza,7.86,7.51,0.35,auralin,36u,42u
47,Jad allah,Gaber,7.97,7.52,0.45,novodra,38u,41u
48,Zak,Kelly,7.66,7.26,0.40,novodra,38u,38u
49,Jackson,Addison,7.99,7.51,0.48,novodra,42u,42u
50,Albinca,Komavec,7.89,7.46,0.43,novodra,41u,39u
51,Kristoffer,Martinsen,9.18,8.64,0.54,auralin,29u,37u
52,Má»¹,Quynh,7.61,7.16,0.45,auralin,57u,64u
53,Nasser,Mansour,7.51,7.06,0.45,novodra,33u,31u
54,Oles,Zhdanov,7.52,7.11,0.41,auralin,54u,67u
55,Triana.,Terrazas,7.71,7.34,0.37,auralin,34u,42u
56,Juliusz,Majewski,7.78,7.31,0.47,novodra,41u,39u
57,Klementyna,SokoÅowska,7.98,7.53,0.45,novodra,42u,41u
58,GabryÅ,Tomaszewski,7.87,7.47,0.40,auralin,29u,37u
59,Leixandre,Alanis,7.74,7.32,0.42,auralin,61u,67u